config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
      sessions: 'users/sessions'
  }
  root 'welcome#index'
  resources :users, only: [:index, :show, :edit, :update, :destroy]
  resources :messages, only: [:create]
  resources :rooms, only: [:create, :index, :show, :edit, :update, :destroy]
  if Rails.env.development? #開発環境の場合
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable#, :confirmable
  validates :name, presence: true, length: { maximum: 10 }
  validates :age, numericality: { only_integer: true,
                      greater_than_or_equal_to: 0, less_than_or_equal_to: 150 }
  validates :self_introduction, length: { maximum: 140 }
  # validates :location, presence: true
  mount_uploader :picture, PictureUploader


  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy

  enum gender_id: { male: 0, female: 1 }
  enum location: {
    北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
    茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
    新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
    岐阜県:21,静岡県:22,愛知県:23,三重県:24,
    滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
    鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
    徳島県:36,香川県:37,愛媛県:38,高知県:39,
    福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,沖縄県:47
  }
  # タグ実装
  acts_as_taggable
  acts_as_taggable_on :skills

  def user_icon
    picture? ? picture_url : "no-image.jpg"
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  def create
    self.resource = warden.authenticate!(auth_options)
    if current_user.name == "ゲスト"
      set_flash_message!(:notice, :signed_in_add)
    else
      set_flash_message!(:notice, :signed_in)
    end
    sign_in(resource_name, resource)
    yield resource if block_given?
    respond_with resource, location: after_sign_in_path_for(resource)
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update, :destory]
  before_action :correct_user, only: [:edit, :update, :destroy]

  def show
    @room = Room.new
    @entry = Entry.new
    @entries = current_user.entries.limit(3) if current_user.id == params[:id].to_i
  end

  def index
    if params[:skill_list].present?
      @users = User.tagged_with(params[:skill_list])
    else
      @users = User.all
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "編集が完了しました"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    flash[:notice] = "ユーザーを削除しました"
    redirect_to root_url
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(*key_names)
    end

    def key_names
      [
        :name,
        :self_introduction,
        :age,
        :picture,
        :skill_list,
        :gender_id,
        :birthday,
        :birthday_public,
        :location
      ]
    end

    def correct_user
      @user = User.find(params[:id])
        unless @user.id == current_user.id
          flash[:alert] = "無効なユーザーです"
          redirect_to users_url
        end
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_profile.html.erb
<p>名前：<%= "#{@user.name}さん" %></p>
<p>性別：<%= @user.gender_id_i18n %></p>
<p>勤務地：<%= @user.location %></p>
<% if @user.birthday_public? && @user.birthday? %>
  <p>誕生日:<%= @user.birthday.to_s(:date) %></p>
<% end %>
<p>自己紹介：<%= @user.self_introduction %></p>
<br>

app/views/users/_tag.html.erb
<p>関連タグ一覧</p>
<% @user.skill_list.each do |tag| %>
  <span class="label label-primary tag-size"><%= tag %></span>
<% end %>
<br><br>
<% if @user.find_related_skills.present? && current_user == @user %>
  <p>関連ユーザー一覧</p>
  <% @user.find_related_skills.limit(5).each do |u| %>
    <%= link_to u.name, u %>
  <% end %>
<% end %>

app/views/users/edit.html.erb
<h1>プロフィール編集</h1>
<hr>
<%= form_for @user do |f| %>
  <%= render "shared/error_messages", object: @user %>
  <%= image_tag @user.user_icon, size: "200x200", class: "set-picture" %>
  <br>
  <p><strong>名前<span class="red">*</span></strong></p>
  <%= f.text_field :name, class: "form-control my-form" %>

  <br>
  <p><strong>性別<span class="red">*</span></strong></p>
  <%= f.select :gender_id, User.gender_ids_i18n.keys.map { |k| [User.gender_ids_i18n[k], k]}, class: "form-control" %>
  <br><br>

  <p><strong>勤務地</strong></p>
  <%= f.select :location, User.locations.keys, {prompt: '選択してください'}, class: 'form-control my-form' %>
  <br>

  <p><strong>誕生日</strong></p>
  <%== sprintf(
  f.date_select(:birthday, use_month_numbers: true, date_separator: '%s',
  start_year: 1930, end_year: Time.now.year, default: '1990-1-1'.to_date), '年','月') + '日生まれ' %>

  <br><br>
  <%= f.label :birthday_public do %>
    <%= f.check_box :birthday_public,{},checked_value = "true", unchecked_value = "false"  %>
    <p class="inline">誕生日を公開する</p>
  <% end %>

  <br><br>

  <p><strong>自己紹介</strong></p>
  <%= f.text_area :self_introduction, class: "form-control my-form" %>

  <br>
  <p><strong>タグ</strong></p>
  <p class="tag-18"><%= text_field_tag 'user[skill_list]', @user.skill_list.join(','),
  "data-role" => "tagsinput", class: "form-control my-form", placeholder: "ruby, php..." %></p>
  <br>
  <p><strong>画像設定</strong></p>
  <%= f.file_field :picture, class: "form-control my-form" %>
  <hr>

  <%= f.submit "登録する", class: "btn btn-primary" %>
<% end %>
<br><br>

app/views/users/index.html.erb
<h1>ユーザー一覧</h1>
<hr>

<%= form_tag(users_path, method: 'get' ) do %>
  <%= text_field_tag :skill_list, '', placeholder: "タグの絞り込み検索ができます", class: "my-form"%>
  <%= submit_tag '絞り込む', class: "btn btn-primary" %>
<% end %>
<% if @users.present? %>
<br><br>
  <% @users.each do |u| %>
    <p>
    <%= image_tag u.picture.url, size: "50x50", class: "set-picture pr-10" if u.picture? %>
    <%= link_to "#{u.name}さん", u %>
    <% u.skill_list.each do |tag| %>
      <span class="label label-primary tag-size"><%= tag %></span>
    <% end %>
    </p>
    <hr>
  <% end %>
<% else %>
  <h2 class="text-danger">ユーザーが見つかりませんでした。</h2>
  <%= link_to "戻る", users_path, class: "btn btn-info" %>
<% end %>
<br>

app/views/users/show.html.erb
<div class="row">
  <div class="col-xs-6">
    <h1>ユーザー情報</h1>
    <hr>
    <div class="parent-user">
      <div class="child-user-one">
        <%= image_tag @user.user_icon, size: "200x200", class: "set-picture" %>
      </div>
      <div class="child-user-two">
        <%= render "profile" %>
        <%= render "tag" %>
      </div>
    </div>
    <hr>
    <% if current_user == @user %>
      <p><%= link_to "ユーザー情報を編集する", edit_user_path, class: "btn btn-success", data: {"turbolinks" => false} %></p>
      <p><%= link_to "ユーザー情報を削除する", @user, class: "btn btn-danger",
            method: :delete, data: { confirm: "本当に削除しますか？" } %></p>
    <% else %>
      <%= form_for @room do |f| %>
          <%= fields_for @entry do |e| %>
            <%= e.hidden_field :user_id, :value => @user.id %>
          <% end %>
        <%= f.submit "チャットを始める", class: "btn btn-warning" %>
      <% end %>
    <% end %>
  </div>
  <% if current_user.id == params[:id].to_i %>
  <div class="col-xs-6">
    <% if @entries.present? %>
      <h1>チャット一覧</h1>
      <hr>
      <% @entries.each do |e| %>
        <p><strong><%= link_to e.room.name, e.room %></strong></p>
        <hr>
      <% end %>
      <%= link_to "チャット一覧へ", rooms_path, class: "btn btn-info" %>
    <% else %>
      <br><br>
      <h3 class="text-danger text-center">まだチャットがありません</h3>
    <% end %>
  </div>
  <% end %>
</div>
<hr>
<p><%= link_to "ユーザー一覧へ", users_path, class: "btn btn-primary" %></p>