config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
      sessions: 'users/sessions'
  }
  root 'welcome#index'
  resources :users, only: [:index, :show, :edit, :update, :destroy]
  resources :messages, only: [:create]
  resources :rooms, only: [:create, :index, :show, :edit, :update, :destroy]
  if Rails.env.development? #開発環境の場合
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/room.rb
class Room < ApplicationRecord
  validates :name, presence: true, length: { maximum: 20 }
  validates :explain, length: { maximum: 140 }
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_room, only: [:show, :edit, :update, :destroy]
  before_action :correct_room_user, only: [:show, :edit, :update, :destroy]

  def index
    @entries = current_user.entries
  end

  def show
    @messages = @room.messages.all
    @message = Message.new
    @entries = @room.entries
    # 既読未読機能
    @messagess = @room.messages.where("(read_flg = ?) AND NOT (user_id = ?)", 0, current_user.id)
    if @messagess.present?
      @messagess.each do |m|
        m.update_attributes(read_flg: 1)
      end
    end
  end

  def create
    @room = Room.create #(params_room)
    @entry1 = @room.entries.create(user_id: current_user.id)
    @entry2 = @room.entries.create(params_entry)
    flash[:notice] = "トークルームを作成しました"
    redirect_to "/rooms/#{@room.id}"
  end

  def edit
  end

  def update
    if @room.update(params_room)
      flash[:notice] = "チャット情報を変更しました"
      redirect_to @room
    else
      render 'edit'
    end
  end

  def destroy
    @room.destroy
    flash[:notice] = "チャットルームを削除しました"
    redirect_to rooms_path
  end

  private

    def set_room
      @room = Room.find(params[:id])
    end

    def params_room
      params.require(:room).permit(:name, :explain)
    end

    def params_entry
      params.require(:entry).permit(:user_id, :room_id)
    end

    def correct_room_user
      unless @room.entries.where(user_id: current_user.id).present?
        flash[:alert] = "無効なユーザーです"
        redirect_back(fallback_location: root_path)
      end
    end

end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/edit.html.erb
<h1>チャット情報の編集</h1>
<hr>
<%= form_for @room do |f| %>
  <%= render "shared/error_messages", object: @room %>
  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control my-form", placeholder: "名前を入力してください" %>
  <br>
  <%= f.label :explain %>
  <%= f.text_area :explain, class: "form-control my-form", size: "30x8", placeholder: "説明を入力してください" %>
  <br>
  <%= f.submit "編集する", class: "btn btn-success" %>
<% end %>
<hr>
<p><%= link_to "戻る", @room, class: "btn btn-primary" %></p>
<p><%= link_to "トップへ", root_path, class: "btn btn-info" %></p>

app/views/rooms/index.html.erb
<h1><%= current_user.name %>さんのチャット一覧</h1>
<hr>
<% if @entries.present? %>
  <% @entries.each do |e| %>
    <%= link_to e.room.name, e.room %>
    <% if e.room.messages.where("(read_flg = ?) AND NOT (user_id = ?)", 0, current_user.id).present? %>
      <%= "(#{e.room.messages.where(read_flg: 0).count})"  %>
    <% end %>
    <hr>
  <% end %>
  <p><%= link_to "トップへ戻る", root_path, class: "btn btn-info" %></p>
<% else %>
  <h2 class="text-danger">まだチャットがありません</h2>
<% end %>

app/views/rooms/show.html.erb
<div class="row">
  <div class="col-xs-3 text-center">
    <h4><%= @room.name %></h4>
    <h4><small><%= @room.explain %></small></h4>
    <hr>
    <h4>参加者</h4>
    <% @entries.each do |e| %>
      <h5><strong><%= link_to "#{e.user.name}さん", e.user %></strong></h5>
    <% end %>
    <p><%= link_to "チャットを編集する", edit_room_path, class: "btn btn-success" %></p>
    <p><%= link_to "チャットを削除する", @room, class: "btn btn-danger",
            method: :delete, data: { confirm: "本当に削除しますか？" } %></p>
  </div>
  <div class="col-xs-9">
    <% if @messages.present? %>
      <% @messages.each do |m| %>
        <% if m.user.id == current_user.id %>
        <h4 class="text-right">
          <p class="alert alert-success">
            <%= m.content %>
            <% if m.read_flg == 0 %>
              <span class="newsign"></span>
            <% end %>
            <br><br>
            <small><string><%= link_to "#{m.user.name}さん", m.user %>
            <%= image_tag m.user.picture.url, size: "60x60", class: "set-picture" if m.user.picture? %>
            </string></small>
          </p>
        </h4>
        <% else %>
        <h4 class="text-left">
          <p class="alert alert-info">
            <%= m.content %><br><br>
            <small><string><%= link_to "#{m.user.name}さん", m.user %>
            <%= image_tag m.user.picture.url, size: "60x60", class: "set-picture" if m.user.picture? %>
            </string></small>
          </p>
        </h4>
        <% end %>
      <% end %>
    <% else %>
      <br>
      <h3 class="text-center">メッセージはまだありません</h3>
      <br>
    <% end %>
    <hr>
    <%= form_for @message do |f| %>
      <%= render "shared/error_messages", object: @message %>
      <%= f.text_field :content, class: "form-control myform", placeholder: "メッセージを入力してください" %>
      <%= f.hidden_field :room_id, :value => @room.id %>
      <hr>
      <div class="text-center">
        <%= f.submit "送信する", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>